### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [NischalSehrawat/Balancing-Bot-Python#1]
Please remove the waiting after a Wire.requestFrom().
These lines: `while(Wire.available() < 6);`
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)
Those lines are in the files "Self-Balancing-Segway-Robot/Arduino_Implementation/Fresh_Bal_Bot/Fresh_Bal_Bot.ino" and "Self-Balancing-Segway-Robot/Arduino_Files/Arduino_Python_Communication.ino".

**Comment by NischalSehrawat** [comment]
Thank you for reviewing the code, I have now commented it out. The code is still in making, so its still not complete and needs a lot of improvements.
